### ISSUE TITLE
maskrcnn_benchmark/data/datasets is missing

### ISSUE THREAD

**Issue by D0ub1ePieR** [yuhuan-wu/RDPNet#2]
Compared to https://github.com/facebookresearch/maskrcnn-benchmark, this folder is missing.
After compiling, the code cannot run correctly.
It will occur 'ImportError: cannot import name 'datasets'.
Is it caused by the missing files?

**Comment by yuhuan-wu** [comment]
I have debugged this issue. It is caused by a wrong `.gitignore` which ignores the update of all `datasets` folders.
Now this code should be installed successfully. Thanks for your report!
