### ISSUE TITLE
Training setting of iSOD dataset

### ISSUE THREAD

**Issue by Patrickctyyx** [yuhuan-wu/RDPNet#3]
Hi, I'm very appreciate of your impressive work! However, I just found something inconsistent about the training setting of iSOD dataset.

In section 4.A of your paper, you said that you use 500 images for training and 200 images for validation. But the JSON file of iSOD of the provided dataset contains 700 images for training. I wonder if the training JSON is not the one used in your paper? Thank you very much.

**Comment by yuhuan-wu** [comment]
Thanks. The final result of s4net is trained with traimval set, i.e. 700 images. We are making fair comparison by training our network on the same set. You can refer to the code of s4net.
