### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by manongXT** [yuhuan-wu/RDPNet#7]
When I run ‘python setup.py build develop', I got this error'RuntimeError: Error compiling objects for extension'
my env ：pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.2
but when I use your env'pytorch==1.1 torchvision==0.2.2 cudatoolkit=9.0',I successfully run the build file.However, when I run the 'demo/visualize.py'file, I got another error'undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E',because the CUDA environment of my system is 10.2.
So I want to ask you, can this code run only when CUDA is 9.0？

**Comment by yuhuan-wu** [comment]
Yes, this error is usually caused by an incompatible CUDA version.
As default, this repo uses system CUDA library to compile the cuda source code. So you need to prepare a same version CUDA library.

**Comment by manongXT** [comment]
But I use the CUDA10.2 Library of the system to run setup.py, but I can't compile it. Do I have to call the CUDA Library of the system back to 9.0?

**Comment by yuhuan-wu** [comment]
> But I use the CUDA10.2 Library of the system to run setup.py, but I can't compile it. Do I have to call the CUDA Library of the system back to 9.0?

Yes. This issue is normal and can be classified to the incompatible version error.  
I recommend to use my default env "pytorch==1.1 torchvision==0.2.2 cudatoolkit=9.0" and make sure the version of the CUDA library (used to compile) is CUDA9.0.

After installing CUDA9.0, you can consider to use my command to conveniently activate CUDA9.0

````
### Write the following code to ~/.bashrc. Use `source ~/.bashrc` to activate it
alias cu102='sudo rm /usr/local/cuda; sudo ln -s /usr/local/cuda-10.2 /usr/local/cuda; echo enable cuda10.2!; nvcc -V'
alias cu101='sudo rm /usr/local/cuda; sudo ln -s /usr/local/cuda-10.1 /usr/local/cuda; echo enable cuda10.1!; nvcc -V'
alias cu92='sudo rm /usr/local/cuda; sudo ln -s /usr/local/cuda-9.2 /usr/local/cuda; echo enable cuda9.2!; nvcc -V'
alias cu90='sudo rm /usr/local/cuda; sudo ln -s /usr/local/cuda-9.0 /usr/local/cuda; echo enable cuda9.0!; nvcc -V'

### Use the following code in the terminal to activate CUDA9.0
cu90
````

Hope this answer will help you a lot.

**Comment by yuhuan-wu** [comment]
If you have further questions, feel free to add my wechat "wyh-hys" with your current university and current position~

**Comment by manongXT** [comment]
OK, thank you for your answer.
